server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/job_tracker
    username: jat
    password: jat
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  threads:
    virtual:
      enabled: true

logging:
  level:
    root: info