services:
  postgres:
    image: postgres:15
    container_name: jat_postgres    
    restart: always
    environment:      
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:      
      - ./pgdata:/var/lib/postgresql/data      
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10  
  # Optional pgAdmin
  # pgadmin:
  #   image: dpage/pgadmin4:8
  #   container_name: jat_pgadmin
  #   depends_on:
  #     postgres:
  #       condition: service_healthy    
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
  #   ports:
  #     - "${PGADMIN_PORT:-8081}:80"
  #   volumes:      
  #     - ./pgadmin_data:/var/lib/pgadmin